"use strict";
const emptyConfiguration=()=>({releases:[],active:[],drafts:[],revisions:[],audit:[],tests:[]});
let configurationData=emptyConfiguration(),configurationEditor=null,promptEditor=null;
let designCategory='production',designQuery='',designMessage='',configurationBusy=false,renderedDesignRoute='',pendingDesignAction=null;
const designLink=(kind,id='',section='')=>'#'+kind+(id?'/'+encodeURIComponent(id):'')+(section?'/'+section:'');
const designName=id=>String(id||'').replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const promptStem=name=>String(name).split('@')[0];
const designButton=(action,text,attributes='')=>`<button data-design="${action}" ${attributes}>${text}</button>`;
function resetConfiguration(){configurationData=emptyConfiguration();configurationEditor=null;promptEditor=null;designMessage='';document.getElementById('design-dialog')?.close();}
async function loadConfiguration(){const version=accessVersion;const result=access.edit_configuration||access.publish_configuration?await api('/api/configuration'):emptyConfiguration();if(version===accessVersion)configurationData=result;}
function designRoute(){const parts=location.hash.slice(1).split('/');return{kind:page(),id:parts[1]?decodeURIComponent(parts[1]):'',section:parts[2]||'overview'};}
function activeRelease(id){const a=configurationData.active.find(a=>a.workflow===id);return configurationData.releases.find(r=>r.id===a?.release_id);}
function editingDrafts(id){return configurationData.drafts.filter(d=>d.bundle.workflow===id&&d.status==='editing');}
function workflowEntries(){const ids=new Set([...Object.keys(state.catalog?.workflows||{}),...configurationData.releases.map(r=>r.workflow),...configurationData.drafts.filter(d=>d.status==='editing').map(d=>d.bundle.workflow)]);return[...ids].map(id=>{const active=activeRelease(id),drafts=editingDrafts(id),latest=active||configurationData.releases.find(r=>r.workflow===id)||drafts[0],definition=latest?.definitions?.[id]||state.catalog?.workflows[id];return{id,active,drafts,latest,definition,fixture:latest?.is_fixture??(definition?.phases?.every(p=>(p.agentProfile||definition.defaults?.agentProfile)==='fixture')??id==='demo')};}).sort((a,b)=>a.id.localeCompare(b.id));}
function promptGroups(){const groups=new Map();for(const r of configurationData.revisions.filter(r=>r.kind==='prompt')){const stem=promptStem(r.name);if(!groups.has(stem))groups.set(stem,[]);groups.get(stem).push(r);}return[...groups].map(([name,versions])=>({name,versions:versions.sort((a,b)=>(Number(b.name.split('@')[1])||0)-(Number(a.name.split('@')[1])||0)||b.created_at.localeCompare(a.created_at))})).sort((a,b)=>a.name.localeCompare(b.name));}
function workflowPromptNames(definitions){return[...new Set(Object.values(definitions).filter(Boolean).flatMap(w=>w.phases.flatMap(p=>p.tasks.map(t=>t.with?.prompt).filter(Boolean))))];}
function promptConsumers(stem){return workflowEntries().filter(w=>w.active&&workflowPromptNames(w.active.definitions||{}).some(n=>promptStem(n)===stem));}
function categoryMatch(fixture){return designCategory==='all'||(designCategory==='fixtures'?fixture:!fixture);}
function designFilters(kind){return`<div class="design-filters"><label>Search ${kind}<input id="design-search" value="${escapeHTML(designQuery)}" placeholder="Search by name or description"></label><label>Show<select id="design-category">${[['production',kind==='workflows'?'Workflows':'Workflow prompts'],['fixtures','Examples & tests'],['all','Everything']].map(([v,n])=>`<option value="${v}" ${designCategory===v?'selected':''}>${n}</option>`).join('')}</select></label></div>`;}
function configurationView(){const r=designRoute();if(r.kind==='prompts'){if(!access.edit_configuration&&!access.publish_configuration)return'<div class="panel design-panel"><h2>Prompt library</h2><p>Configuration access is required to read or edit instructions.</p><button data-connect>Connect workspace access</button></div>';return r.id?promptDetail(r.id):promptList();}return r.id?workflowDetail(r.id,r.section):workflowList();}
function workflowList(){const all=workflowEntries(),entries=all.filter(w=>categoryMatch(w.fixture)&&`${w.id} ${w.definition?.description||''}`.toLowerCase().includes(designQuery.toLowerCase()));return`<div class="design-heading"><div><h2>Your workflows</h2><p>Open a workflow to review its design, continue a draft, or inspect previous releases.</p></div><div class="design-actions">${access.edit_configuration?designButton('import','Import')+designButton('new-workflow','New workflow','class="primary"'):''}</div></div>${designFilters('workflows')}<div class="panel design-panel"><table class="design-table"><thead><tr><th>Workflow</th><th>Active release</th><th>Draft</th><th>Updated</th><th></th></tr></thead><tbody>${entries.map(w=>`<tr><td><a class="design-title" href="${designLink('workflows',w.id)}">${escapeHTML(designName(w.id))}</a><p>${escapeHTML(w.definition?.description||'Workflow draft')}</p>${w.fixture?'<span class="badge">Example / test</span>':''}</td><td>${w.active?'Release '+w.active.release_number:w.definition&&!configurationData.releases.length?(state.catalog?.configuration_source==='files'?'Local definition':'Active definition'):'Not active'}</td><td>${w.drafts.length?`<a href="${designLink('workflows',w.id,'draft')}">Continue editing${w.drafts.length>1?' · '+w.drafts.length+' drafts':''}</a>`:'—'}</td><td>${escapeHTML(w.latest?.actor||'')}<br><small>${date(w.latest?.updated_at||w.latest?.created_at)}</small></td><td><a href="${designLink('workflows',w.id)}">Open →</a></td></tr>`).join('')}</tbody></table>${!entries.length?empty('No workflows in this view','Choose Examples & tests to see fixture workflows, or create a workflow.'):''}</div><p class="subtle">${all.filter(w=>w.fixture).length} example and test workflows are grouped separately. Published releases and execution history are retained.</p>`;}
function phaseOverview(d){return`<ol class="design-phases">${(d?.phases||[]).map(p=>`<li><div><strong>${escapeHTML(designName(p.id))}</strong><span>${p.gate?'Human approval required':'Automatic'}</span></div><p>${p.tasks.map(t=>escapeHTML(t.uses.replaceAll('.',' · '))).join(' → ')}</p>${p.tasks.filter(t=>t.with?.prompt).map(t=>`<small>Instructions: ${escapeHTML(designName(promptStem(t.with.prompt)))}</small>`).join('')}</li>`).join('')}</ol>`;}
function workflowDetail(id,section){const w=workflowEntries().find(w=>w.id===id);if(!w&&configurationEditor?.bundle.workflow!==id)return empty('Workflow not found');const head=`<a class="design-back" href="#workflows">← All workflows</a><div class="design-heading"><div><h2>${escapeHTML(designName(id))}</h2><p>${escapeHTML(w?.definition?.description||'Design a new workflow')}</p></div><span class="badge">${w?.active?'Release '+w.active.release_number+' active':'Not active'}</span></div><nav class="design-tabs" aria-label="Workflow sections">${['overview','draft','versions','runs'].map(t=>`<a href="${designLink('workflows',id,t)}" ${t===section?'aria-current="page"':''}>${designName(t)}</a>`).join('')}</nav>`;if(section==='draft')return head+draftWorkspace(id);if(section==='versions')return head+workflowVersions(id);if(section==='runs')return head+`<div class="panel design-panel"><h3>Recent runs</h3><p>Normal executions and draft tests visible to your account.</p>${jobTable(state.jobs.filter(j=>j.workflow===id))}</div>`;return head+`<div class="design-two-columns"><section class="panel design-panel"><div class="design-heading"><h3>How this workflow runs</h3>${access.edit_configuration?designButton('start-edit',w?.drafts.length?'Continue editing':'Edit workflow',`data-workflow="${escapeHTML(id)}" class="primary"`):''}</div>${phaseOverview(w?.definition)}</section><aside><section class="panel design-panel"><h3>Instructions</h3>${workflowPromptNames(w?.active?.definitions||{[id]:w?.definition}).map(n=>`<a class="design-prompt-link" href="${designLink('prompts',promptStem(n))}">${escapeHTML(designName(promptStem(n)))}<small>${escapeHTML(n)}</small></a>`).join('')||'<p>No prompts yet.</p>'}</section><section class="panel design-panel"><h3>Release behaviour</h3><p>New jobs use the active release. Existing jobs, retries and follow-ups retain their original instructions.</p></section></aside></div>`;}
function workflowVersions(id){const releases=configurationData.releases.filter(r=>r.workflow===id),active=activeRelease(id);return`<div class="panel design-panel"><h3>Release history</h3><p>Compare a release before making it active. Restoration affects future jobs only.</p>${releases.map(r=>`<article class="design-version"><div><h4>Release ${r.release_number} ${r.id===active?.id?'<span class="badge active">Active</span>':''}</h4><p>${escapeHTML(r.note)}</p><small>${escapeHTML(r.actor)} · ${date(r.created_at)}</small></div><div class="design-actions">${designButton('compare','Compare',`data-release="${r.id}"`)}${designButton('export','Export',`data-release="${r.id}"`)}${access.publish_configuration&&r.id!==active?.id?designButton('activation',configurationData.audit.some(a=>a.release_id===r.id)?'Restore this release':'Activate release',`data-release="${r.id}"`):''}</div></article>`).join('')||'<p>No published releases yet.</p>'}</div><div class="panel design-panel"><h3>Activation history</h3>${configurationData.audit.filter(a=>a.workflow===id).map(a=>`<p><strong>Release ${configurationData.releases.find(r=>r.id===a.release_id)?.release_number||'—'}</strong> · ${escapeHTML(a.actor)} · ${date(a.created_at)}<br>${escapeHTML(a.note)}</p>`).join('')||'<p>No activations yet.</p>'}</div>`;}
function promptList(){const groups=promptGroups().filter(g=>{const users=promptConsumers(g.name);return categoryMatch(users.length>0&&users.every(w=>w.fixture))&&`${g.name} ${g.versions[0].content}`.toLowerCase().includes(designQuery.toLowerCase());});return`<div class="design-heading"><div><h2>Instruction library</h2><p>Edit instructions once, then choose the workflows that should adopt them.</p></div>${access.publish_configuration?designButton('new-prompt','New prompt','class="primary"'):''}</div>${designFilters('prompts')}<div class="design-prompt-grid">${groups.map(g=>`<a class="panel design-prompt-card" href="${designLink('prompts',g.name)}"><div><h3>${escapeHTML(designName(g.name))}</h3><span class="badge">Revision ${escapeHTML(g.versions[0].name.split('@')[1])}</span></div><p>${escapeHTML(g.versions[0].content.slice(0,160))}${g.versions[0].content.length>160?'…':''}</p><small>${promptConsumers(g.name).length} active workflows · ${date(g.versions[0].created_at)}</small></a>`).join('')}</div>${!groups.length?empty('No prompts in this view','Choose another category or create a prompt.'):''}`;}
function promptDetail(stem){const g=promptGroups().find(g=>g.name===stem),latest=g?.versions[0];if(!g&&promptEditor?.name!==stem)return empty('Prompt not found');const consumers=promptConsumers(stem);if(promptEditor?.name===stem)return promptEditingView(consumers);return`<a class="design-back" href="#prompts">← All prompts</a><div class="design-heading"><div><h2>${escapeHTML(designName(stem))}</h2><p>Revision ${escapeHTML(latest.name.split('@')[1])} · ${escapeHTML(latest.actor)} · ${date(latest.created_at)}</p></div>${access.publish_configuration?designButton('edit-prompt','Edit prompt',`data-prompt="${escapeHTML(stem)}" class="primary"`):''}</div><div class="design-two-columns"><section class="panel design-panel"><h3>Instructions</h3><div class="design-instructions">${renderMarkdown(latest.content)}</div></section><aside><section class="panel design-panel"><h3>Used by</h3>${consumers.map(w=>`<a class="design-prompt-link" href="${designLink('workflows',w.id)}">${escapeHTML(designName(w.id))}<small>${workflowPromptNames(w.active.definitions).filter(n=>promptStem(n)===stem).map(escapeHTML).join(', ')}</small></a>`).join('')||'<p>Not used by an active workflow yet.</p>'}</section><section class="panel design-panel"><h3>Version history</h3>${g.versions.map(r=>`<details><summary>Revision ${escapeHTML(r.name.split('@')[1])} · ${date(r.created_at)}</summary><p>${escapeHTML(r.note)}</p>${diffHTML(r.content,latest.content,'This revision','Latest')}</details>`).join('')}</section></aside></div>`;}
function promptEditingView(consumers){const e=promptEditor;return`<a class="design-back" href="#prompts">← All prompts</a><div class="design-heading"><div><h2>Edit ${escapeHTML(designName(e.name))}</h2><p>A new revision is assigned automatically. Existing releases stay unchanged.</p></div>${designButton('cancel-prompt','Cancel')}</div><div class="design-two-columns"><section class="panel design-panel"><label>Instructions<textarea id="design-prompt-content" rows="18">${escapeHTML(e.content)}</textarea></label><label>What changed and why?<input id="design-prompt-note" value="${escapeHTML(e.note)}"></label><details><summary>Review changes</summary>${diffHTML(e.original,e.content)}</details></section><aside class="panel design-panel"><h3>Adopt in workflows</h3><p>Selected workflows receive a draft for review. Their active release will not change.</p>${consumers.map(w=>`<label class="design-check"><input type="checkbox" data-consumer="${escapeHTML(w.id)}" ${e.consumers.includes(w.id)?'checked':''} ${w.drafts.length||!access.edit_configuration?'disabled':''}><span>${escapeHTML(designName(w.id))}<small>${w.drafts.length?'Has a draft: adopt from that draft':!access.edit_configuration?'Editor access required':'Create a workflow draft'}</small></span></label>`).join('')||'<p>No active workflows use this prompt.</p>'}<button data-design="save-prompt" class="primary">Publish prompt revision</button><p class="subtle">You can also publish without selecting any workflows.</p></aside></div>`;}
function baseForBundle(b){const a=configurationData.audit.find(a=>a.workflow===b.workflow&&a.generation===b.base_generation);return configurationData.releases.find(r=>r.id===a?.release_id)?.bundle||activeRelease(b.workflow)?.bundle||{workflows:{},prompts:{}};}
function editorState(bundle,draft,definitions){return{id:draft?.id||crypto.randomUUID(),revision:draft?.revision||0,bundle:structuredClone(bundle),base:structuredClone(baseForBundle(bundle)),definitions:structuredClone(definitions||{}),step:'edit',selected:Object.keys(bundle.prompts)[0]||'',advanced:false,workflowFile:bundle.workflow,dirty:!draft,digest:null,note:'',testKey:null};}
function openDraft(bundle,draft=null,definitions={}){configurationEditor=editorState(bundle,draft,definitions);designMessage='';location.hash=designLink('workflows',bundle.workflow,'draft');renderDesign(true);}
function draftWorkspace(id){
 if(!access.edit_configuration&&!access.publish_configuration)return'<div class="panel design-panel"><p>Configuration access is required to manage drafts.</p></div>';
 if(configurationEditor?.bundle.workflow!==id){const drafts=editingDrafts(id);if(drafts.length===1){const d=drafts[0];configurationEditor=editorState(d.bundle,d,d.definitions);}else return`<div class="panel design-panel"><h3>${drafts.length?'Choose a draft':'No changes in progress'}</h3>${drafts.map(d=>`<article class="design-version"><div><strong>Draft by ${escapeHTML(d.actor)}</strong><p>${date(d.updated_at)}</p></div>${designButton('resume-draft','Continue editing',`data-draft="${d.id}"`)}</article>`).join('')}${!drafts.length&&access.edit_configuration?designButton('start-edit','Start editing',`data-workflow="${escapeHTML(id)}" class="primary"`):''}</div>`;}
 const e=configurationEditor,steps=['edit','review','check','publish'];let body='';
 const controls=`<div class="design-stepper" aria-label="Release steps">${steps.map((s,i)=>`<button data-design="step" data-step="${s}" ${e.step===s?'aria-current="step"':''}>${i+1}. ${s==='check'?'Check & test':designName(s)}</button>`).join('')}</div>`;
 if(e.step==='edit')body=`<div class="design-editor-layout"><aside class="panel design-panel"><h3>Workflow phases</h3>${phaseOverview(e.definitions[id])}<h3>Prompts</h3>${Object.keys(e.bundle.prompts).map(n=>`<button class="design-file ${e.selected===n&&!e.advanced?'selected':''}" data-design="select-prompt" data-prompt="${escapeHTML(n)}">${escapeHTML(designName(promptStem(n)))}</button>`).join('')}<hr>${designButton('advanced',e.advanced?'Back to instructions':'Advanced YAML')}<details><summary>Local development</summary>${designButton('export-draft','Export draft bundle')}</details></aside><section class="panel design-panel">${e.advanced?`<h3>Advanced workflow definition</h3><p>Define phases, inputs, gates and capabilities. Versions are assigned during review.</p><label>Workflow<select id="design-workflow-file">${Object.keys(e.bundle.workflows).map(n=>`<option ${n===e.workflowFile?'selected':''} value="${escapeHTML(n)}">${escapeHTML(designName(n))}</option>`).join('')}</select></label><label>YAML<textarea id="design-yaml" ${!access.edit_configuration?'readonly':''} spellcheck="false" rows="22">${escapeHTML(e.bundle.workflows[e.workflowFile]||'')}</textarea></label><details><summary>Add dependencies</summary><label>Prompt or workflow ID<input id="design-dependency-name" placeholder="research@4 or follow-up-workflow"></label>${designButton('add-prompt','Add library prompt')}${designButton('add-workflow','Add workflow YAML')}</details>`:`<h3>${escapeHTML(designName(promptStem(e.selected)))||'Instructions'}</h3><p>Edit the instructions below. New revision numbers and workflow references are handled automatically.</p>${e.selected?`<label>Instructions<textarea id="design-instructions" ${!access.edit_configuration?'readonly':''} rows="19">${escapeHTML(e.bundle.prompts[e.selected])}</textarea></label><label>Adopt a published revision<select id="design-adopt" ${!access.edit_configuration?'disabled':''}><option value="">Keep these instructions</option>${configurationData.revisions.filter(r=>r.kind==='prompt'&&promptStem(r.name)===promptStem(e.selected)).map(r=>`<option value="${escapeHTML(r.name)}">${escapeHTML(r.name)}</option>`).join('')}</select></label>`:'<p>This workflow has no prompts. Add a prompt reference through Advanced YAML.</p>'}`}</section></div>`;
 else if(e.step==='review')body=`<section class="panel design-panel"><h3>Review the changes</h3><p>New versions have been assigned where needed. These changes apply only to this workflow release and its dependencies.</p>${bundleDiff(e.base,e.bundle)}<p>Next, validate and optionally run a fixture test.</p></section>`;
 else if(e.step==='check'){const tests=configurationData.tests.filter(t=>t.draft_id===e.id);body=`<div class="panel design-panel"><h3>Checks for this candidate</h3><div class="design-check-result"><strong>${e.digest?'✓ Definition validation passed':'Definition validation needed'}</strong><p>Checks references, permissions, profiles and workflow structure. No model has run.</p>${designButton('validate','Validate again')}</div><div class="design-check-result"><h4>Execution test</h4><p>Fixture tests use local-demo and fixture agents. They do not evaluate live-model quality.</p>${access.edit_configuration?designButton('test','Run fixture test'):''}${tests.map(t=>`<div class="design-test"><span class="badge">${escapeHTML(label(t.status))}</span><span>${t.candidate_digest===e.digest?'Current candidate':'Earlier candidate — instructions changed'}</span><button data-job="${t.job_id}">Open test run</button><small>${date(t.created_at)}</small></div>`).join('')||'<p>No recorded tests for this draft.</p>'}</div></div>`;}
 else body=`<div class="panel design-panel design-publish"><h3>Publish this workflow release</h3><p>${e.digest?'Definitions validated.':'Validate the current draft before publishing.'} ${configurationData.tests.some(t=>t.draft_id===e.id&&t.candidate_digest===e.digest&&t.status==='succeeded')?'A fixture test passed for this candidate.':'No successful fixture test is recorded for this candidate.'}</p><label>What changed and why?<textarea id="design-release-note" rows="3" placeholder="Describe the reason for this change">${escapeHTML(e.note)}</textarea></label><div class="design-publish-options"><article><h4>Use it for new jobs</h4><p>Publish and activate a release. Existing jobs retain their original instructions.</p>${access.publish_configuration?designButton('publish-active','Publish and activate','class="primary"'):''}</article><article><h4>Save it for later</h4><p>Publish without changing the active release.</p>${access.publish_configuration?designButton('publish-only','Publish only'):''}</article></div>${!access.publish_configuration?'<p>A configuration publisher can publish this saved draft.</p>':''}</div>`;
 return`<div class="design-draft-status"><span id="design-save-status">${e.dirty?'● Unsaved changes':'✓ Saved draft'}</span><span>Based on ${e.bundle.base_generation?'activation '+e.bundle.base_generation:'a new workflow'}</span><div>${access.edit_configuration?designButton('save','Save draft'):''}${e.revision&&access.edit_configuration?designButton('discard','Discard draft'):''}</div></div>${controls}${body}<div class="design-bottom-actions">${e.step!=='edit'?designButton('back-step','← Back'):''}${e.step!=='publish'?designButton('next-step',e.step==='edit'?'Review changes →':e.step==='review'?'Check & test →':'Continue to publish →','class="primary"'):''}</div>`;
}
function lineDiff(before,after){const a=String(before||'').split('\n'),b=String(after||'').split('\n');let start=0;while(start<a.length&&start<b.length&&a[start]===b[start])start++;let endA=a.length,endB=b.length;while(endA>start&&endB>start&&a[endA-1]===b[endB-1]){endA--;endB--;}return[...a.slice(0,start).map(text=>({type:'same',text})),...a.slice(start,endA).map(text=>({type:'removed',text})),...b.slice(start,endB).map(text=>({type:'added',text})),...a.slice(endA).map(text=>({type:'same',text}))];}
function diffHTML(before,after,beforeLabel='Previous',afterLabel='Proposed'){if(before===after)return'<p class="subtle">No changes.</p>';return`<div class="design-diff" aria-label="Changes"><div class="design-diff-key"><span>− ${escapeHTML(beforeLabel)}</span><span>+ ${escapeHTML(afterLabel)}</span></div><pre>${lineDiff(before,after).map(l=>`<span class="diff-${l.type}">${l.type==='added'?'+':l.type==='removed'?'−':' '} ${escapeHTML(l.text)}</span>`).join('')}</pre></div>`;}
function bundleDiff(before,after){const sections=[];for(const kind of['workflows','prompts']){const old=before[kind]||{},next=after[kind]||{},keys=new Set([...Object.keys(old).map(n=>kind==='prompts'?promptStem(n):n),...Object.keys(next).map(n=>kind==='prompts'?promptStem(n):n)]);for(const key of keys){const oldNames=Object.keys(old).filter(n=>(kind==='prompts'?promptStem(n):n)===key),newNames=Object.keys(next).filter(n=>(kind==='prompts'?promptStem(n):n)===key),oldText=oldNames.map(n=>old[n]).join('\n'),newText=newNames.map(n=>next[n]).join('\n');if(oldText!==newText||oldNames.join()!==newNames.join())sections.push(`<details open class="design-change"><summary>${escapeHTML(designName(key))} <small>${escapeHTML(oldNames.join(', ')||'New')} → ${escapeHTML(newNames.join(', ')||'Removed')}</small></summary>${diffHTML(oldText,newText)}</details>`);}}return sections.join('')||'<p>No content changes.</p>';}
function renderDesign(force=false){if(!['workflows','prompts'].includes(page()))return;const focus=document.activeElement;if(!force&&configurationBusy)return;if(!force&&renderedDesignRoute===location.hash&&$('content').contains(focus)&&focus?.matches('input,textarea,select'))return;const selection=focus?.id==='design-search'?focus.selectionStart:null;setHTML($('content'),`<div class="design-workspace">${designMessage?`<div class="notice" role="status">${escapeHTML(designMessage)}</div>`:''}${configurationView()}</div>`);renderedDesignRoute=location.hash;if(selection!==null&&$('design-search')){$('design-search').focus();$('design-search').setSelectionRange(selection,selection);}}
async function configRequest(path,method,body){const version=accessVersion,response=await fetch('/api/configuration'+path,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${sessionStorage.getItem('factory-observer-token')||''}`},body:JSON.stringify(body)}),result=await response.json();if(version!==accessVersion)throw Error('Workspace access changed. Reopen the editor.');if(!response.ok)throw Error(result.error||'Configuration request failed');return result;}
function configDownload(bundle){const url=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`${bundle.workflow}-bundle.json`;a.click();URL.revokeObjectURL(url);}
function designDialog(title,body){let d=$('design-dialog');if(!d){d=document.createElement('dialog');d.id='design-dialog';d.className='configuration-dialog';document.body.append(d);}d.innerHTML=`<div class="design-panel"><div class="design-heading"><h2>${escapeHTML(title)}</h2>${designButton('close-dialog','✕','aria-label="Close dialog"')}</div>${body}<p id="design-dialog-error" role="status"></p></div>`;if(!d.open)d.showModal();}
function markDesignDirty(){const e=configurationEditor;if(e){e.dirty=true;e.digest=null;e.testKey=null;}if($('design-save-status'))$('design-save-status').textContent='● Unsaved changes';}
async function saveDesignDraft(){const e=configurationEditor;if(!access.edit_configuration)throw Error('Editor access is required to save changes.');const saved=await configRequest('/drafts/'+e.id,'PUT',{revision:e.revision,bundle:e.bundle});e.revision=saved.revision;e.dirty=false;await loadConfiguration();}
async function prepareDesign(){const e=configurationEditor;if(!access.edit_configuration){const result=await configRequest('/validate','POST',e.bundle);e.digest=result.digest;return;}const prepared=await configRequest('/prepare','POST',e.bundle);if(JSON.stringify(e.bundle)!==JSON.stringify(prepared.bundle))e.dirty=true;const stem=promptStem(e.selected);e.bundle=prepared.bundle;e.definitions=prepared.definitions;e.selected=Object.keys(e.bundle.prompts).find(n=>promptStem(n)===stem)||Object.keys(e.bundle.prompts)[0]||'';await saveDesignDraft();e.digest=prepared.digest;}
function adoptPrompt(e,name){const r=configurationData.revisions.find(r=>r.kind==='prompt'&&r.name===name);if(!r)throw Error('Prompt revision not found');const old=e.selected;for(const[id,w]of Object.entries(e.definitions)){let changed=false;for(const t of w.phases.flatMap(p=>p.tasks))if(t.with?.prompt===old){t.with.prompt=name;changed=true;}if(changed)e.bundle.workflows[id]=JSON.stringify(w,null,2);}delete e.bundle.prompts[old];e.bundle.prompts[name]=r.content;e.selected=name;markDesignDirty();}
function newWorkflowBundle(id,template){if(template){const r=activeRelease(template),bundle=structuredClone(r.bundle),definitions=structuredClone(r.definitions),root=definitions[template];delete definitions[template];root.id=id;root.version=1;definitions[id]=root;for(const w of Object.values(definitions))for(const f of w.followUps||[])if(f.workflow===template)f.workflow=id;bundle.workflow=id;bundle.base_generation=0;bundle.workflows=Object.fromEntries(Object.entries(definitions).map(([k,w])=>[k,JSON.stringify(w,null,2)]));return{bundle,definitions};}const w={apiVersion:'factory/v1',kind:'Workflow',id,version:1,description:'Describe what this workflow does.',inputs:{issue:{type:'issue_ref'},repository:{type:'repository_ref'}},defaults:{workerProfile:'fixture-standard',agentProfile:'fixture',repositoryRevision:'pin_at_job_start'},phases:[{id:'research',timeout:'10m',permissions:[],tasks:[{uses:'agent.execute',with:{prompt:id+'@1',output:'research.md'}},{uses:'artifact.publish',with:{name:'research',path:'research.md'}}]}]};return{bundle:{format:1,workflow:id,base_generation:0,workflows:{[id]:JSON.stringify(w,null,2)},prompts:{[id+'@1']:'Describe the task and required output.'}},definitions:{[id]:w}};}
document.addEventListener('input',event=>{const el=event.target,e=configurationEditor;if(el.id==='design-search'){designQuery=el.value;renderDesign(true);return;}if(el.id==='design-instructions'&&e){e.bundle.prompts[e.selected]=el.value;markDesignDirty();}if(el.id==='design-yaml'&&e){e.bundle.workflows[e.workflowFile]=el.value;markDesignDirty();}if(el.id==='design-release-note'&&e)e.note=el.value;if(el.id==='design-prompt-content'&&promptEditor)promptEditor.content=el.value;if(el.id==='design-prompt-note'&&promptEditor)promptEditor.note=el.value;});
document.addEventListener('change',event=>{const el=event.target,e=configurationEditor;if(el.id==='design-prompt-content'&&promptEditor){const diff=document.querySelector('.design-two-columns details');if(diff)diff.innerHTML='<summary>Review changes</summary>'+diffHTML(promptEditor.original,promptEditor.content);}if(el.id==='design-category'){designCategory=el.value;renderDesign(true);}if(el.id==='design-workflow-file'&&e){e.workflowFile=el.value;renderDesign(true);}if(el.id==='design-adopt'&&el.value&&e){adoptPrompt(e,el.value);renderDesign(true);}if(el.dataset.consumer&&promptEditor)promptEditor.consumers=el.checked?[...promptEditor.consumers,el.dataset.consumer]:promptEditor.consumers.filter(id=>id!==el.dataset.consumer);});
window.addEventListener('beforeunload',event=>{if(configurationEditor?.dirty||promptEditor){event.preventDefault();event.returnValue='';}});
document.addEventListener('click',async event=>{
 const button=event.target.closest('[data-design]');if(!button||configurationBusy)return;const action=button.dataset.design;configurationBusy=true;$('content').inert=true;
 try{const e=configurationEditor;
 if(action==='save-leave'||action==='discard-leave'){if(action==='save-leave')await saveDesignDraft();configurationEditor=null;promptEditor=null;$('design-dialog').close();location.hash=pendingDesignNavigation;pendingDesignNavigation=null;return;}
 if(action==='close-dialog'){$('design-dialog').close();return;}
 if(action==='new-workflow'){designDialog('Create a workflow',`<label>Workflow name<input id="design-new-id" placeholder="customer-research"></label><label>Start from<select id="design-template"><option value="">Simple fixture example</option>${workflowEntries().filter(w=>w.active).map(w=>`<option value="${escapeHTML(w.id)}">${escapeHTML(designName(w.id))}</option>`).join('')}</select></label><p>You can edit instructions and inspect phases before publishing.</p>${designButton('create-workflow','Create draft','class="primary"')}`);return;}
 if(action==='create-workflow'){const id=$('design-new-id').value.trim().toLowerCase().replace(/\s+/g,'-');if(!/^[a-z0-9_-]{1,80}$/.test(id))throw Error('Use letters, numbers and hyphens for the workflow name.');if(workflowEntries().some(w=>w.id===id))throw Error('That workflow already exists. Open it to continue editing.');const created=newWorkflowBundle(id,$('design-template').value);$('design-dialog').close();openDraft(created.bundle,null,created.definitions);await saveDesignDraft();renderDesign(true);return;}
 if(action==='start-edit'){const id=button.dataset.workflow,drafts=editingDrafts(id);if(drafts.length){configurationEditor=null;location.hash=designLink('workflows',id,'draft');renderDesign(true);return;}const r=activeRelease(id)||configurationData.releases.find(r=>r.workflow===id);if(!r)throw Error('No release available to edit');const bundle=await api(`/api/configuration/releases/${r.id}/export`);openDraft(bundle,null,r.definitions);await saveDesignDraft();renderDesign(true);return;}
 if(action==='resume-draft'){const d=configurationData.drafts.find(d=>d.id===button.dataset.draft);openDraft(d.bundle,d,d.definitions);return;}
 if(action==='select-prompt'){const stem=promptStem(button.dataset.prompt);if(e.advanced)await prepareDesign();e.selected=Object.keys(e.bundle.prompts).find(n=>promptStem(n)===stem)||button.dataset.prompt;e.advanced=false;renderDesign(true);return;}
 if(action==='advanced'){if(e.advanced)await prepareDesign();e.advanced=!e.advanced;renderDesign(true);return;}
 if(action==='save'){await saveDesignDraft();designMessage='Draft saved.';renderDesign(true);return;}
 if(['step','next-step','back-step'].includes(action)){const steps=['edit','review','check','publish'],target=action==='step'?button.dataset.step:steps[steps.indexOf(e.step)+(action==='next-step'?1:-1)];if(target!=='edit'&&(!e.digest||e.dirty))await prepareDesign();e.step=target;designMessage='';renderDesign(true);return;}
 if(action==='validate'){await prepareDesign();designMessage='Definition validation passed for the saved candidate.';renderDesign(true);return;}
 if(action==='test'){if(!e.digest||e.dirty)await prepareDesign();e.testKey=e.testKey||crypto.randomUUID();await configRequest(`/drafts/${e.id}/test`,'POST',{revision:e.revision,key:e.testKey,submission:{workflow:e.bundle.workflow,repository:'local-demo',issue:{provider:'fixture',key:'DRAFT-'+e.testKey,title:'Workflow draft test',body:'Fixture execution of the saved candidate.'}}});await loadConfiguration();designMessage='Test started. Its status is shown below.';renderDesign(true);return;}
 if(action==='publish-only'||action==='publish-active'){if(!e.digest||e.dirty)throw Error('Review and validate the saved candidate before publishing.');const id=e.bundle.workflow;await configRequest('/releases','POST',{bundle:e.bundle,note:e.note,draft_id:e.id,draft_revision:e.revision,activate:action==='publish-active'});configurationEditor=null;await loadConfiguration();designMessage=action==='publish-active'?'Release published and activated for new jobs.':'Release published. The active release is unchanged.';location.hash=designLink('workflows',id,'versions');renderDesign(true);return;}
 if(action==='discard'){designDialog('Discard this draft?',`<p>This removes the draft from work in progress. Published releases and runs are retained.</p>${designButton('confirm-discard','Discard draft')}`);return;}
 if(action==='confirm-discard'){await configRequest(`/drafts/${e.id}/discard`,'POST',{revision:e.revision});const id=e.bundle.workflow;configurationEditor=null;$('design-dialog').close();await loadConfiguration();designMessage='Draft discarded.';location.hash=designLink('workflows',id);renderDesign(true);return;}
 if(action==='export'||action==='export-draft'){configDownload(action==='export'?await api(`/api/configuration/releases/${button.dataset.release}/export`):e.bundle);return;}
 if(action==='import'){designDialog('Import a local bundle','<label>Bundle JSON<input type="file" id="design-import-file" accept=".json"></label><p>Imports open as drafts and never replace the active release.</p>');$('design-import-file').onchange=async()=>{try{const file=$('design-import-file').files[0];if(file.size>2_000_000)throw Error('Bundle must be smaller than 2 MB');const bundle=JSON.parse(await file.text()),prepared=await configRequest('/prepare','POST',bundle);$('design-dialog').close();openDraft(prepared.bundle,null,prepared.definitions);await saveDesignDraft();renderDesign(true);}catch(err){if($('design-dialog-error'))$('design-dialog-error').textContent=err.message;else{designMessage=err.message;renderDesign(true);}}};return;}
 if(action==='add-prompt'){const name=$('design-dependency-name').value.trim(),r=configurationData.revisions.find(r=>r.kind==='prompt'&&r.name===name);if(!r)throw Error('Enter an exact published prompt name, such as research@4.');e.bundle.prompts[name]=r.content;markDesignDirty();designMessage='Prompt added. Reference it in YAML before reviewing.';renderDesign(true);return;}
 if(action==='add-workflow'){const id=$('design-dependency-name').value.trim(),r=activeRelease(id);if(!r)throw Error('Enter an active workflow ID.');for(const [key,value]of Object.entries(r.bundle.workflows))if(!Object.hasOwn(e.bundle.workflows,key))e.bundle.workflows[key]=value;for(const[key,value]of Object.entries(r.bundle.prompts))if(!Object.hasOwn(e.bundle.prompts,key))e.bundle.prompts[key]=value;for(const[key,value]of Object.entries(r.definitions))if(!Object.hasOwn(e.definitions,key))e.definitions[key]=structuredClone(value);markDesignDirty();designMessage='Dependencies added. Connect the follow-up in YAML before reviewing.';renderDesign(true);return;}
 if(action==='compare'||action==='activation'){const r=configurationData.releases.find(r=>r.id===button.dataset.release),active=activeRelease(r.workflow),wasActive=configurationData.audit.some(a=>a.release_id===r.id),a=configurationData.active.find(a=>a.workflow===r.workflow);pendingDesignAction={release:r.id,generation:a?.generation||0,workflow:r.workflow};designDialog(action==='compare'?`Compare release ${r.release_number}`:`${wasActive?'Restore':'Activate'} release ${r.release_number}`,`<p>${escapeHTML(designName(r.workflow))} · ${escapeHTML(r.note)}</p>${bundleDiff(active?.bundle||{workflows:{},prompts:{}},r.bundle)}${action==='activation'?`<p>Only new jobs use this release. Existing jobs retain their original instructions.</p><label>Reason<input id="design-activation-note"></label>${designButton('confirm-activation',wasActive?'Restore this release':'Activate release','class="primary"')}`:''}`);return;}
 if(action==='confirm-activation'){const a=pendingDesignAction;await configRequest(`/releases/${a.release}/activate`,'POST',{expected_generation:a.generation,note:$('design-activation-note').value});$('design-dialog').close();await loadConfiguration();designMessage='Active release updated for future jobs.';renderDesign(true);return;}
 if(action==='new-prompt'){designDialog('Create a prompt',`<label>Prompt name<input id="design-new-prompt" placeholder="research"></label>${designButton('create-prompt','Continue','class="primary"')}`);return;}
 if(action==='create-prompt'){const name=$('design-new-prompt').value.trim().toLowerCase().replace(/\s+/g,'-');if(!/^[a-z0-9_-]{1,80}$/.test(name))throw Error('Use letters, numbers and hyphens for the prompt name.');if(promptGroups().some(g=>g.name===name))throw Error('That prompt already exists. Open it to edit.');promptEditor={name,content:'',original:'',note:'',expected:null,consumers:[]};$('design-dialog').close();location.hash=designLink('prompts',name);renderDesign(true);return;}
 if(action==='edit-prompt'){const r=promptGroups().find(g=>g.name===button.dataset.prompt).versions[0];promptEditor={name:promptStem(r.name),content:r.content,original:r.content,note:'',expected:r.name,consumers:[]};renderDesign(true);return;}
 if(action==='cancel-prompt'){promptEditor=null;renderDesign(true);return;}
 if(action==='save-prompt'){const p=promptEditor,result=await configRequest('/prompts/revise','POST',{name:p.name,content:p.content,note:p.note,expected_name:p.expected,consumers:p.consumers.map(workflow=>({workflow,expected_generation:configurationData.active.find(a=>a.workflow===workflow)?.generation||0}))});promptEditor=null;await loadConfiguration();designMessage=`Published ${result.name}. ${result.drafts.length?result.drafts.length+' workflow drafts are ready for review.':'No workflow releases were changed.'}`;renderDesign(true);return;}
 }catch(error){if($('design-dialog')?.open)$('design-dialog-error').textContent=error.message;else{designMessage=error.message;renderDesign(true);}}finally{configurationBusy=false;$('content').inert=false;}
});

let pendingDesignNavigation=null;
document.addEventListener('click',event=>{
 const link=event.target.closest('a[href^="#"]');
 if(!link||link.getAttribute('href')===location.hash)return;
 const unsavedPrompt=promptEditor&&(promptEditor.content!==promptEditor.original||promptEditor.note);
 if(!configurationEditor?.dirty&&!unsavedPrompt)return;
 event.preventDefault();event.stopImmediatePropagation();pendingDesignNavigation=link.getAttribute('href');
 designDialog('Unsaved changes',`<p>Keep editing, or save your workflow draft before leaving. Unsaved prompt-library edits will be lost if you leave.</p>${configurationEditor?.dirty&&!unsavedPrompt?designButton('save-leave','Save draft and leave','class="primary"'):''}${designButton('discard-leave','Leave without saving')}${designButton('close-dialog','Keep editing')}`);
},true);
